//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBDiff {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DBDiff.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Source=.;Initial Catalog=dbName;Integrated Security=True;.
        /// </summary>
        internal static string ConnectionString {
            get {
                return ResourceManager.GetString("ConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT s.name + &apos;.&apos; + p.name AS name
        ///FROM
        ///	sys.procedures AS p
        ///	INNER JOIN sys.schemas AS s ON s.schema_id = p.schema_id
        ///WHERE (is_ms_shipped = 0)
        ///ORDER BY s.name + &apos;&apos; + p.name.
        /// </summary>
        internal static string Procedures {
            get {
                return ResourceManager.GetString("Procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE PROC [dbo].[sp_helptable] (
        ///@tableName sysname = NULL --The table name for which the script will be genrated else for all tables
        ///, @schemaName sysname = NULL --Specify the schema name else table of same name from all schema will be genrated
        ///, @includeDBName BIT = 1 -- Do you want to include use database name in the definition script?
        ///, @includeForeignKey BIT = 1 -- Do you want to include foreignkeys in the definition script?
        ///, @includeDefault BIT = 1 --Do you want to include default constraints  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string sp_helptable {
            get {
                return ResourceManager.GetString("sp_helptable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IF EXISTS (SELECT name FROM sys.procedures WHERE name = N&apos;sp_helptable&apos;)
        ///	BEGIN
        ///		SELECT 1 AS sprocExists
        ///	END
        ///ELSE
        ///	BEGIN
        ///	    SELECT 0 AS sprocExists
        ///	END.
        /// </summary>
        internal static string sp_helptable_exists {
            get {
                return ResourceManager.GetString("sp_helptable_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT s.name + &apos;.&apos; + t.name AS name
        ///FROM
        ///	sys.tables AS t
        ///	INNER JOIN sys.schemas AS s ON s.schema_id = t.schema_id
        ///WHERE (is_ms_shipped = 0)
        ///ORDER BY s.name + &apos;&apos; + t.name.
        /// </summary>
        internal static string Tables {
            get {
                return ResourceManager.GetString("Tables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT s.name + &apos;.&apos; + v.name AS name
        ///FROM
        ///	sys.views AS v
        ///	INNER JOIN sys.schemas AS s ON s.schema_id = v.schema_id
        ///WHERE (is_ms_shipped = 0)
        ///ORDER BY s.name + &apos;&apos; + v.name.
        /// </summary>
        internal static string Views {
            get {
                return ResourceManager.GetString("Views", resourceCulture);
            }
        }
    }
}
